cask "font-fira-code-nerd-font"
# cask "arc"
cask "alacritty"
cask "raycast"

brew "fzf"
brew "npm"
brew "stow"
brew "antidote"
brew "zoxide"
brew "nvm"
brew "starship"
brew "tmux"
brew "tpm"
brew "lazygit"
brew "gpg"
brew "nvim"
brew "ripgrep"
brew "fd"
brew "lsd"
brew "jq"

tap "koekeishiya/formulae"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"
