"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$cmd_duration $time\
$line_break\
$character"""

[cmd_duration]
format = ' [󱎫 $duration]($style) '

[nodejs]
format = "[$symbol($version )]($style)"

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_metrics]
disabled = false

[time]
disabled = false
format = "[$time]($style)"

[fill]
symbol = " "
