import = [
    "~/.config/alacritty/gruvbox_dark.toml"
]

live_config_reload = true

[window]
decorations = "Buttonless"

[window.padding]
x = 12
y = 12

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"
